### ISSUE TITLE
Where should I write my own token??

### ISSUE THREAD

**Issue by knito** [Logerfo/gitlab-notifications#1]
Hi,

Where should I write this code... Should I create some file with that entry?? some json in somewhere?

> {
>     "gitlab-notifications.privateToken": "YOUR-TOKEN"
> }

**Comment by Logerfo** [comment]
Sorry for taking so long to answer this, my github notifications was badly configured. The code is supposed to be on the `settings.json` file. You can open this file through the "Preferences: Open Settings (JSON)" command in the palette.
I'm closing this, but feel free to reply if you have any extra questions.

**Comment by vivektyagi999** [comment]
I'm using angular 6. I didn't get where i have to write this token.

**Comment by Logerfo** [comment]
@vivektyagi999 I don't understand... you know this is a VSCode extension, right?

**Comment by vivektyagi999** [comment]
@Logerfo I know this is a VSCode. My Question is where I have to mention this code?

**Comment by Logerfo** [comment]
Like I said [here](https://github.com/Logerfo/gitlab-notifications/issues/1#issuecomment-465608016), there is a file called `settings.json`, which holds all your VS Code settings and also its extensions settings. The token is one of them.

**Comment by vivektyagi999** [comment]
I'm using angular version 6. which doesn't have setting.json. It have package.json.  Is it fine if i write token or local gitlab url in package.json ?

**Comment by vivektyagi999** [comment]
Thanks @Logerfo

**Comment by rilesdun** [comment]
Just ran into this issue myself today - Here is a clear way to solve this:
- Install gitlab notifications extension
-  Under `Extensions` ---> `Installed` ---> `Gitlab Notifications` ---> Click the little cog ---> `Extensions Settings` 
- You will see fourth option is to set your personal token
