### ISSUE TITLE
Support environment variable for token

### ISSUE THREAD

**Issue by CHEF-KOCH** [Logerfo/gitlab-notifications#23]
I like to [sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) my VS Code settings and it would be cool if you could provide GitLab token through env vars. Via environment variable an user would not expose his token to the public.

**Comment by Logerfo** [comment]
I also use the extension you mentioned, but the gist created is private, so I don't mind exposing tokens. Anyway, do you have any other extension that does what you want so I can take a look as an example?

**Comment by CHEF-KOCH** [comment]
You can choose to use an existent repo (public) [like it did](https://gist.github.com/CHEF-KOCH/b18b44e5ef6a2c5776e1dc72f14e6ea0) or create a new one, which is (as you said) private.

**Comment by Logerfo** [comment]
Alright, I'll try to work on this on Monday. Thanks!

**Comment by Logerfo** [comment]
Should be available at [0.0.8](https://github.com/Logerfo/gitlab-notifications/releases/tag/0.0.8).
