### ISSUE TITLE
How can I install this notification?

### ISSUE THREAD

**Issue by stefaneidelloth** [Logerfo/gitlab-notifications#24]
I am a gitlab newbe. Can I use this extension with 

Project => Settings => Integrations?

If yes, what url should I enter and which events should I enable?

If not, what is the right way to use gitlab-notifications?

![image](https://user-images.githubusercontent.com/12675339/76506542-a0200800-644b-11ea-9b22-212088161d69.png)

**Comment by Logerfo** [comment]
No, this extension does not use web hooks, it uses personal tokens. Web hooks are repository scoped, while personal tokens are user scoped. You can use [this link](https://gitlab.com/profile/personal_access_tokens) to generate it if you're using gitlab.com.

**Comment by stefaneidelloth** [comment]
Just for clarification: is this 
a) some visual studio code extension or 
b) an extension of Gitlab itself?
I use a gitlab instance that is hosed by our company.

Also see

https://stackoverflow.com/questions/60651173/how-to-show-gitlab-notifications-online-in-status-tool-bar

**Comment by Logerfo** [comment]
This is a Visual Studio Code extension.
